version: "3.8"

volumes:
  db-data:
  tmp-date:
  log-date:
  public-date:

services:
  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: ${WORKDIR}
    command: yarn start
    volumes:
      - ./frontend:/${WORKDIR}
    ports:
      - "${FRONTEND_PORT}:3000"
    stdin_open: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: ${WORKDIR}
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      API_DOMEIN: localhost:${FRONTEND_PORT}
    volumes:
      - ./backend:/${WORKDIR}
      - tmp-date:/${WORKDIR}/tmp
      - log-date:/${WORKDIR}/log
    ports:
      - "${BACKEND_PORT}:3000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    volumes:
      - public-date:/${WORKDIR}/public
      - tmp-date:/${WORKDIR}/tmp
    environment:
      WORKDIR: ${WORKDIR}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Aisa/Tokyo
    ports:
      - "3306:3306"
