version: "3.8"

volumes:
  tmp-date:
  log-date:
  public-date:

services:
  frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: ${WORKDIR}
    command: yarn start
    environment:
      REACT_APP_IP_ADDR: ${IP_ADDR}
    volumes:
      - ./frontend:/${WORKDIR}
    ports:
      - "${FRONTEND_PORT}:3000"
    stdin_open: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: ${WORKDIR}
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      API_DOMEIN: ${IP_ADDR}:${FRONTEND_PORT}
    volumes:
      - ./backend:/${WORKDIR}
      - tmp-date:/${WORKDIR}/tmp
      - log-date:/${WORKDIR}/log

  nginx:
    build:
      context: nginx
    volumes:
      - public-date:/${WORKDIR}/public
      - tmp-date:/${WORKDIR}/tmp
    command: /bin/sh -c "envsubst '$$HOME $$IP_ADDR' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'  -c /etc/nginx/nginx.conf"
    environment:
      HOME: ${WORKDIR}
      IP_ADDR: ${IP_ADDR}
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - backend
